export { authApi } from "./api/authApi";
export {
  useLoginMutation,
  useRegisterMutation,
  useVerifyEmailMutation,
  useForgotPasswordMutation,
  useResetPasswordMutation,
  useChooseRoleMutation,
  useSaveDoctorProfileMutation,
  useUploadDocumentMutation,
  useSubmitOnboardingMutation,
  useOnboardingStatus,
  useChangeEmailMutation,
  useChangePasswordMutation,
  authKeys,
} from "./model/useAuthMutations";
export type {
  User,
  LoginRequest,
  LoginResponse,
  RegisterRequest,
  RegisterResponse,
  VerifyEmailRequest,
  VerifyEmailResponse,
  ForgotPasswordRequest,
  ResetPasswordRequest,
  OnboardingStatus,
  OnboardingNextStep,
  AuthMeResponse,
  ChooseRoleRequest,
  ChooseRoleResponse,
  DoctorProfileRequest,
  ChangeEmailRequest,
  ChangePasswordRequest,
  ApiError,
} from "./types";
